<a href="https://colab.research.google.com/github/sungrae98/Machine-Learning/blob/main/DL_01_MyFirstDL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# !pip install tensorflow

# 버전 확인
import tensorflow as tf

tf.__version__

'2.13.0'

In [ ]:
# 회귀분석 기초_가장 훌륭한 예측선 그리기

# 최소제곱법

import numpy as np
import pandas as pd

# 공부한 시간, 성적 >> 각각 x, y 변수에 넣기

x = np.array([2,4,6,8])
y = np.array([81,93,91,97])

In [ ]:
print(x)
print()
print(y)

[2 4 6 8]

[81 93 91 97]


In [ ]:
# x. y의 평균값 구하기

x.mean() # (2+4+6+8) / 4

5.0

In [ ]:
np.mean(x)

5.0

In [ ]:
mx = np.mean(x)
my = np.mean(y)

In [ ]:
print('x의 평균값: ', mx)
print('y의 평균값:', my)

x의 평균값:  5.0
y의 평균값: 90.5


In [ ]:
x

array([2, 4, 6, 8])

In [ ]:
x[0]

2

In [ ]:
# 기울기 공식 : y = wx + b 구하기

# 기울기의 분모 구하기

[(i - mx) ** 2  for i in x]

[9.0, 1.0, 1.0, 9.0]

In [ ]:
sum([(i - mx) ** 2  for i in x])

20.0

In [ ]:
divisor = sum([(i - mx) ** 2  for i in x])

In [ ]:
len(x) # x의 크기

4

In [ ]:
# 기울기의 분자 구하기

def top(x, mx, y, my):
    d = 0
    for i in range(len(x)):
      d += (x[i]-mx)*(y[i]-my)
    return d


In [ ]:
top(x, mx, y, my)

46.0

In [ ]:
dividend = top(x, mx, y, my)

In [ ]:
print('분모: ', divisor)
print('분자: ', dividend)

분모:  20.0
분자:  46.0


In [ ]:
# 평균 제곱 오차 구하기

w = dividend / divisor

# 절편
b = my - (mx*w)

print("기울기 w: ", w)
print('y 절편 b: ', b)
print('가장 훌륭한 예측선: %.2f X + %d 이다'%(w,b))

기울기 w:  2.3
y 절편 b:  79.0
가장 훌륭한 예측선: 2.30 X + 79 이다


In [ ]:
# 평균제곱오차

# 임의의 가상의 기울기 값 w, y절편 b 입력

w = 3
b = 76

x = np.array([2,4,6,8])
y = np.array([81,93,91,97])

In [ ]:
# 예측 함수 생성(pred = wx + b)

def predict(x):
    return w*x + b

# 예측값이 들어갈 빈 리스트 생성

result = []

for i in range(len(x)):
    result.append(predict(x[i]))
    print('공부한 시간: %.2f, 실제 점수: %.2f, 예측점수: %.2f'%(x[i], y[i], predict(x[i])))

공부한 시간: 2.00, 실제 점수: 81.00, 예측점수: 82.00
공부한 시간: 4.00, 실제 점수: 93.00, 예측점수: 88.00
공부한 시간: 6.00, 실제 점수: 91.00, 예측점수: 94.00
공부한 시간: 8.00, 실제 점수: 97.00, 예측점수: 100.00


In [ ]:
# 평균 제곱 오차(mse) 함수 이용, 각 y 값 대입 >> 최종값 구하기

n = len(x)

def mse(y, y_pred):
    return (1/n)*sum((y - y_pred)**2)

# 평균제곱오차 출력
print('평균제곱오차(mse):' + str(mse(y, result)))

평균제곱오차(mse):11.0
